package com.nexora.riendas.entities.enums;

public enum AuditEventType {
    USUARIO_CREADO,
    CUENTA_REGISTRADA,
    MANDATO_CREADO,
    MANDATO_REVOCADO,
    CONTACTO_CREADO,
    CONTACTO_EDITADO,
    CONTACTO_ARCHIVADO,
    CHAT_RECIBIDO,
    IA_RESPUESTA,
    IA_ERROR,
    PROPUESTA_CREADA,
    VALIDACION_OK,
    VALIDACION_RECHAZADA,
    APROBACION_SOLICITADA,
    APROBACION_APROBADA,
    APROBACION_RECHAZADA,
    APROBACION_EXPIRADA,
    FIRMA_SOLICITADA,
    TX_CONFIRMADA,
    TX_FALLIDA,
    ATAQUE_DEMO,
    LLAVE_ROTADA,
    MOVIMIENTO_NO_RECONOCIDO,
    ALERTA_CONFIRMADA,
    LLAVE_COMPROMETIDA
}
